version: '3'
services:

  server:
    build: server
    
    restart: always
    ports:
      - ${KRUS_WEB_PORT}:80
    links:
      - db
      # Host machine directory:docker-webdirectory
    volumes:
      - /Users/jsolsvik/git/kruskontroll/imt2291-prosjekt2-v2018/server:/var/www/html

    depends_on:
      - db

    environment:
      KRUS_DB_HOST: db

  db:
    image: mysql:5.7
    restart: always
    volumes:
      - ./db:/var/lib/mysql

    # There migth be an mysql instance running on 3306 on host machine already
    ports:
      - ${KRUS_DB_PORT}:3306
    environment:
      MYSQL_DATABASE: mvc
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

#https://perchrunway.com/blog/2017-01-19-getting-started-with-docker-for-local-development